require 'rake/testtask'
require 'rspec/core/rake_task'

Rake::TestTask.new do |t|
  t.libs.push "lib"
  t.test_files = FileList['tests/*_test.rb']
  t.verbose = true
end

RSpec::Core::RakeTask.new do |s|
  s.pattern = "specs/**/*_spec.rb"
end